### ISSUE TITLE
メモ

### ISSUE THREAD

**Issue by B4129** [rexiaxm7/report-service-web#18]
追加したい実装
* チーム内に月報を〇〇日までに提出していないユーザーがいればアイコンや色で強調表示する
* チームリーダー(そもそもそういう権限あるか確認）がいれば未提出のユーザーがチームに所属している場合画面表示時にアラートなりポップアップを出す仕組みを作りたい
* 月報未提出ユーザーにはメールかSlackかTeamsか無言電話をかける

**Comment by B4129** [comment]
https://github.com/facebook/react/issues/14620
Contextのネスト解消法（Atomic designだとpropsで値を渡していくのは厳しい部分が多いかも）

**Comment by rexiaxm7** [comment]
@B4129 
これの内容を１つ１つのIssueにしてenhancementにする方がいいと思います。

**Comment by B4129** [comment]
issueに直したので閉じます！
