### ISSUE TITLE
API定義をOpenAPI形式で作成する

### ISSUE THREAD

**Issue by rexiaxm7** [rexiaxm7/report-service-web#2]

**Comment by B4129** [comment]
generate tool の調査

**Comment by B4129** [comment]
https://tech.smarthr.jp/entry/2020/08/25/135631

OpenAPI Generator をDockerで立ち上げてソースをぶっこぬくのが良いみたい
変更を検知してgenerateを実行するパッケージもあるのでそれを使いたい場合はプロジェクトに直接OpenAPI Generatorを入れればよさそう

**Comment by B4129** [comment]
docker-composeup時にコードを出力するように変更

別コマンド等で実行できるようにした方が良い？
