### ISSUE TITLE
コミットのprefixをemojiにすると可読性があがるかどうか

### ISSUE THREAD

**Issue by rexiaxm7** [rexiaxm7/report-service-web#32]
commitのprefixが読みにくいと感じることが多々あるのでemojiにするのはどうかな？
種類が多すぎると使いづらいので、慣れるまでは５分類くらいでやるといいような気がしています。
PRでfeatureをマージする場合はSquash Mergeが理想なので、PRコメント的なイメージの方が強いと思いますが・・・

下記記事程度
https://qiita.com/Jung0/items/0a9a7a97a2c17f92d3c5

**Comment by B4129** [comment]
https://github.com/rexiaxm7/report-service-web/pull/34
で実装してみました
